### ISSUE TITLE
Suggesting to add some more acronyms

### ISSUE THREAD

**Issue by soujanya1997** [mkfeuhrer/acrons#11]
TBH - To be honest
HMB - Hit me back.
HMU - Hit me up.
IDC - I don't care
SAAS - Software as a service
NVM - Never Mind

**Comment by mkfeuhrer** [comment]
Thanks for your suggestions! 
It would be great if you can raise a PR for this? Also, remove the 2 character acronyms!

If not, I'll add it in some time.
